Additions and changes for trailers
matthiasbeyer/git-dit pull request #1
Opened 2017-03-15 17:53 UTC by neithernut

2017-03-15 17:54 UTC, neithernut commented
The implementation of `Trailers::next()` could be improved. Documentation is missing, too.

2017-03-16 08:08 UTC, matthiasbeyer requested changes
Besides the changes you suggested, here are my annotations.

2017-03-16 08:08 UTC, matthiasbeyer commented on lib/src/message/line.rs
> +use std::str::Lines as L;
Don't rename this, it is absolutely confusing reading `L` in the code and not finding an generic around. You use it only one time anyways.

2017-03-16 08:08 UTC, matthiasbeyer commented on lib/src/message/line.rs
> +            static ref RE: Regex = Regex::new(r"^(?P<key>(.*)):\ (?P<value>(.*))$").unwrap();
I guess `[[:^space:]]` [would do](https://docs.rs/regex/0.2.1/regex/).

2017-03-16 08:08 UTC, matthiasbeyer commented on lib/src/message/line.rs
> +            if let (Some(key), Some(value)) = (cap.name("key"), cap.name("value")) {
Could it be that

```rust
if let (Some(Key), Some(value)) = RE.captures(trimmed).map(|c| (c.name("key"), c.name("value))) {
```

would do?

2017-03-16 08:08 UTC, matthiasbeyer commented on lib/src/message/line.rs
> +pub struct Lines<'a>(Peekable<L<'a>>);
(See above.)

2017-03-16 08:08 UTC, matthiasbeyer commented on lib/src/message/line.rs
> +#[derive(Debug, Clone)]
I am not sure whether we need `Clone` here. Also I'm not sure whether this would actually work as intended...

2017-03-16 08:08 UTC, matthiasbeyer commented on lib/src/message/line.rs
> +                let mut t = trailer;
I guess you can leave this out if you match against `Some(Line::Trailer(mut trailer))`.

2017-03-16 08:08 UTC, matthiasbeyer commented on lib/src/message/trailer.rs
> +    pub fn append(self, slice: &str) -> TrailerValue {
Maybe a comment that this automatically turns everything into a `TrailerValue::String`?

2017-03-16 08:08 UTC, matthiasbeyer commented on lib/src/message/trailer.rs
> +            loop {
I would use [loop labels](https://doc.rust-lang.org/book/loops.html#loop-labels) so one can easily see which loop a `break` is for.

2017-03-16 10:12 UTC, neithernut commented on lib/src/message/trailer.rs
> +            loop {
Still not sure whether I'll rewrite the entire method.

2017-03-16 11:25 UTC, neithernut commented on lib/src/message/trailer.rs
> +            loop {
The thing has to be rewritten because the logic for text lines is erroneous.

2017-03-16 11:57 UTC, neithernut commented
I'm thinking of introducing yet another type in order to simplify `Trailers`: a `TrailerCollector` enum to encapsulate the state necessary for scanning a block. A value `Collecting` would wrap a `LinkedList` (maybe as a reference) for collection. A function would append to the wrapped list or ignore the argument for other cases.

2017-03-16 12:16 UTC, matthiasbeyer requested changes

2017-03-16 12:16 UTC, matthiasbeyer commented on lib/src/message/line.rs
> +            static ref RE: Regex = Regex::new(r"^(?P<key>([^[:space]]+)):\ (?P<value>(.*))$").unwrap();
Missing ending `:` in char class `space`.

2017-03-16 15:06 UTC, matthiasbeyer approved these changes

2017-03-16 15:06 UTC, matthiasbeyer commented
Ready to squash from my POV.

2017-03-16 15:44 UTC, neithernut commented
Done.

2017-03-17 09:19 UTC, matthiasbeyer commented
Was ff-merged in https://github.com/neithernut/git-dit/pull/35 - doesn't close here because of rebase.

2017-03-17 09:20 UTC, closed without merging